const express = require('express');
const router = express.Router();
const Category = require('../schemas/categories');

const asyncHandler = fn => (req, res, next) => {
  Promise.resolve(fn(req, res, next)).catch(next);
};

// create category with basic validation
router.post('/', asyncHandler(async (req, res) => {
  const { name, slug } = req.body;
  if (!name) {
    return res.status(400).json({ message: 'name is required' });
  }
  // allow slug to be auto-generated by schema hook
  const category = new Category({ ...req.body });
  const saved = await category.save();
  res.status(201).json(saved);
}));

// list categories
router.get('/', asyncHandler(async (req, res) => {
  const list = await Category.find({ isDeleted: false });
  res.json(list);
}));

// get by id
router.get('/:id', asyncHandler(async (req, res) => {
  const cat = await Category.findById(req.params.id);
  if (!cat || cat.isDeleted) return res.status(404).json({ message: 'Category not found' });
  res.json(cat);
}));

// update
router.put('/:id', asyncHandler(async (req, res) => {
  const cat = await Category.findByIdAndUpdate(req.params.id, req.body, { new: true, runValidators: true });
  if (!cat || cat.isDeleted) return res.status(404).json({ message: 'Category not found' });
  res.json(cat);
}));

// soft delete
router.delete('/:id', asyncHandler(async (req, res) => {
  const cat = await Category.findByIdAndUpdate(req.params.id, { isDeleted: true }, { new: true });
  if (!cat) return res.status(404).json({ message: 'Category not found' });
  res.json({ message: 'Category deleted' });
}));

module.exports = router;